version: '2'
services:
  wifi-connect:
    build: ./wifi-connect
    network_mode: "host"
    privileged: true
    labels:
      io.resin.features.dbus: '1'
  ssids:
    build: ./ssids
    privileged: true
    restart: always
    labels:
      io.resin.features.dbus: '1'
