FROM resin/%%RESIN_MACHINE_NAME%%-debian:buster

ENV INITSYSTEM on

RUN apt-get update \
    && apt-get install -y libnm-dev python3-gi \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY ssids.py .

COPY show-wifi-networks.py .

ENV DBUS_SYSTEM_BUS_ADDRESS unix:path=/host/run/dbus/system_bus_socket

CMD ["python3", "ssids.py"]
