FROM resin/%%RESIN_MACHINE_NAME%%-debian:stretch

ENV INITSYSTEM on

RUN apt-get update \
    && apt-get install -y dbus-python \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY ssids.py .

CMD ["python", "ssids.py"]
