FROM resin/%%RESIN_MACHINE_NAME%%-debian:buster

ENV INITSYSTEM on

RUN apt-get update \
    && apt-get install -y dbus libnm-dev python3-gi \
    && systemctl mask dbus.service \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY ssids.py .

ENV DBUS_SYSTEM_BUS_ADDRESS unix:path=/host/run/dbus/system_bus_socket
ENV PYTHONIOENCODING utf-8

CMD ["python3", "ssids.py"]
